### ISSUE TITLE
Significantly Slower Inference Time with LoRA

### ISSUE THREAD

**Issue by X1AOX1A** [verl-project/verl#1857]
### Issue

When using LoRA tuning, we observe **significantly increased time** for the following operations compared to full fine-tuning:

- **Computing rollouts**
- **Running tests**

This leads to a higher per-step runtime and longer overall training time.

Is this expected behavior, possibly due to additional computation or inefficiencies introduced by LoRA in the `vllm` backend?

> Please ignore the save_checkpoint speed due to hareward differences on different machines

#### Logs on GSM8K with Qwen2.5-1.5B

<img width="1472" alt="Image" src="https://github.com/user-attachments/assets/5ebd9348-ee8a-41d5-afa6-6b2ffeae7a7d" />
<img width="478" alt="Image" src="https://github.com/user-attachments/assets/42cd048b-b668-4077-9bba-3d6e26b45f54" />

#### Logs on Countdown with Qwen2.5-1.5B

<img width="1535" alt="Image" src="https://github.com/user-attachments/assets/1833fb69-9d59-409f-a00f-3f58f6741555" />

### Configuration Details

All configurations are identical between full fine-tuning and LoRA tuning, except for the LoRA-specific settings.

#### Model

- **Base**: `Qwen/Qwen2.5-1.5B-Instruct`
- **Dataset**: GSM8K
- **Hardward**: 8xL40-48G

------

#### Full Fine-Tuning Config

```yaml
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_files: data/gsm8k/train.parquet
  val_files: data/gsm8k/test.parquet
  train_batch_size: 1024
  max_prompt_length: 512
  max_response_length: 1024
  filter_overlong_prompts: true
  truncation: error
  shuffle: false

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-1.5B-Instruct
    use_remove_padding: true
    enable_gradient_checkpointing: true
  actor:
    optim:
      lr: 3e-6
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 40
    use_kl_loss: true
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0
    fsdp_config:
      param_offload: false
      optimizer_offload: false
  rollout:
    log_prob_micro_batch_size_per_gpu: 128
    tensor_model_parallel_size: 1
    name: vllm
    gpu_memory_utilization: 0.8
    n: 5
    load_format: safetensors
    layered_summon: true
  ref:
    log_prob_micro_batch_size_per_gpu: 128
    fsdp_config:
      param_offload: true

trainer:
  critic_warmup: 0
  logger: ['console', 'wandb']
  project_name: verl_grpo_example_gsm8k
  experiment_name: qwen2.5_1.5b_grpo_2
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 20
  test_freq: 5
  total_epochs: 15
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
```

------

#### LoRA Tuning Config

```yaml
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

data:
  train_files: data/gsm8k/train.parquet
  val_files: data/gsm8k/test.parquet
  train_batch_size: 1024
  max_prompt_length: 512
  max_response_length: 1024
  filter_overlong_prompts: true
  truncation: error
  shuffle: false

actor_rollout_ref:
  model:
    path: Qwen/Qwen2.5-1.5B-Instruct
    lora_rank: 64
    lora_alpha: 32
    use_remove_padding: true
    enable_gradient_checkpointing: true
  actor:
    optim:
      lr: 3e-6
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 40
    use_kl_loss: true
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0
    fsdp_config:
      param_offload: false
      optimizer_offload: false
  rollout:
    log_prob_micro_batch_size_per_gpu: 128
    tensor_model_parallel_size: 1
    name: vllm
    gpu_memory_utilization: 0.8
    n: 5
    load_format: safetensors
    layered_summon: true
  ref:
    log_prob_micro_batch_size_per_gpu: 128
    fsdp_config:
      param_offload: true

trainer:
  critic_warmup: 0
  logger: ['console', 'wandb']
  project_name: verl_grpo_example_gsm8k
  experiment_name: qwen2.5_1.5b_grpo_lora_2
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 20
  test_freq: 5
  total_epochs: 15
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
```
